esphome:
  name: esphome_ir
  friendly_name: ESP1
  platformio_options:
    build_flags: 
      - -D_IR_ENABLE_DEFAULT_=false -DSEND_HAIER_AC=true -DSEND_HAIER_AC160=true -DDECODE_HAIER_AC160=true
  includes: 
    - heiko/heiko_ir.h
  libraries:
    - IRremoteESP8266

esp8266:
  board: d1_mini


# Enable logging
logger:


# Enable Home Assistant API
api:
  encryption:
    key: ""


ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


i2c:


remote_transmitter:
  pin: D6
  carrier_duty_percent: 50%


remote_receiver:
  pin:
    number: D7
    inverted: true
  dump: haier


climate:
  - platform: custom
    lambda: |-
      auto bedroom_ac = new HeikoAC();
      bedroom_ac->set_temp_sensor(id(current_temperature));
      App.register_component(bedroom_ac);
      return {bedroom_ac};
    climates:
      - name: "Schlafzimmer Klima"   


#
button:
  - platform: template
    name: "Schlafzimmer Klima Licht"
    on_press:
      - lambda: |-
          ac.setLightToggle(true);
          ac.send();


# 
sensor:
  - platform: sht3xd
    temperature:
      name: "Schlafzimmer Temperatur"
      id: current_temperature
    humidity:
      name: "Schlafzimmer Feuchtigkeit"
    address: 0x45
    update_interval: 60s
